POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Nota creada desde Rest Client 2",
  "important": true,
  "userId": "6086c1d2e5fc0606e2b965a7"
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Nota creada desde Rest Client",
  "userId": "6086c1d2e5fc0606e2b965a7"
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "important": true
}